const achievementConfig = {
  mash: [
    { name: "Keyboard Novice", type: "mash", amount: 1, tooltip: "You've just begun mashing those keys!" },
    { name: "Caffeinated Coder", type: "mash", amount: 10, tooltip: "The coffee is starting to kick in!" },
    { name: "Code Connoisseur", type: "mash", amount: 50, tooltip: "You're getting the hang of this coding thing!" },
    { name: "Syntax Samurai", type: "mash", amount: 100, tooltip: "Your coding skills are swift like a samurai!" },
    { name: "Keyboard Maestro", type: "mash", amount: 200, tooltip: "You're the master of the keyboard symphony!" },
    { name: "Mash Magician", type: "mash", amount: 500, tooltip: "You can conjure code with a flick of your wrist!" },
    { name: "Code Wizard", type: "mash", amount: 1000, tooltip: "You're weaving magic spells with your code!" },
    { name: "Keyboard God", type: "mash", amount: 5000, tooltip: "You've ascended to the realm of the coding deities!" },
    { name: "Error Terminator", type: "mash", amount: 10000, tooltip: "No error can escape your coding prowess!" },
    { name: "Debugging Guru", type: "mash", amount: 50000, tooltip: "You can debug code with your eyes closed!" },
    { name: "Codezilla", type: "mash", amount: 100000, tooltip: "You're a legendary monster of code!" },
    { name: "Mashinator", type: "mash", amount: 200000, tooltip: "You mash with relentless determination!" },
    { name: "Code Whisperer", type: "mash", amount: 500000, tooltip: "You speak the language of code fluently!" },
    { name: "Mash Picasso", type: "mash", amount: 1000000, tooltip: "You turn code into beautiful works of art!" },
    { name: "Quantum Coder", type: "mash", amount: 5000000, tooltip: "You've entered the quantum realm of coding!" },
    { name: "Mashitect", type: "mash", amount: 10000000, tooltip: "You architect code with elegance and precision!" },
    { name: "Code Whisperer", type: "mash", amount: 50000000, tooltip: "You listen to the code and bring it to life!" },
    { name: "Mash Magician", type: "mash", amount: 100000000, tooltip: "You can make code disappear and reappear at will!" },
    { name: "Master of Mash", type: "mash", amount: 500000000, tooltip: "You've achieved mastery in the art of mashing!" },
    { name: "Keyboard Legend", type: "mash", amount: 1000000000, tooltip: "Your name will be whispered for generations to come!" },
  ],
  total: [
    { name: "Making Progress", type: "total", amount: 1, tooltip: "You're on the path to coding greatness!" },
    { name: "Coding Voyager", type: "total", amount: 100, tooltip: "You're exploring the vast coding universe!" },
    { name: "Code Titan", type: "total", amount: 500, tooltip: "Your coding skills have reached monumental proportions!" },
    { name: "Coding Dynamo", type: "total", amount: 1000, tooltip: "Your coding energy is electrifying!" },
    { name: "Code Commander", type: "total", amount: 5000, tooltip: "You command an army of lines of code!" },
    { name: "Coding Overlord", type: "total", amount: 10000, tooltip: "You rule the coding kingdom with an iron fist!" },
    { name: "Code Dictator", type: "total", amount: 50000, tooltip: "Your coding decree is law!" },
    { name: "Coding Legend", type: "total", amount: 100000, tooltip: "Your coding skills are the stuff of legends!" },
    { name: "Coding Deity", type: "total", amount: 500000, tooltip: "You've ascended to the divine realm of coding!" },
    { name: "Code Apocalypse", type: "total", amount: 1000000, tooltip: "Your code brings about the end of bugs!" },
    { name: "Code Insanity", type: "total", amount: 5000000, tooltip: "Your coding skills drive others crazy with envy!" },
    { name: "Coding Mastermind", type: "total", amount: 10000000, tooltip: "You're a genius architect of code!" },
    { name: "Code Almighty", type: "total", amount: 50000000, tooltip: "You possess the power to bend code to your will!" },
    { name: "Coding Immortal", type: "total", amount: 100000000, tooltip: "Your coding legacy will never fade away!" },]
  };
export default achievementConfig;
